services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sg_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
      - ./scripts:/scripts
    networks:
      - db-internal

  auth-service:
    image: sg-auth-service
    build:
      context: .
      dockerfile: src/Services/AuthService/SG.AuthService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SG_Financial_AuthDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_SECRET_KEY}
    networks:
      - db-internal
      - api-internal
    depends_on:
      - sqlserver

  account-service:
    image: sg-account-service
    build:
      context: .
      dockerfile: src/Services/AccountService/SG.AccountService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SG_Financial_AccountDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_SECRET_KEY}
    networks:
      - db-internal
      - api-internal
    depends_on:
      - sqlserver

  api-gateway:
    image: sg-api-gateway
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET_KEY}
    networks:
      - api-internal
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      - auth-service
      - account-service
  
networks:
  api-internal:
    driver: bridge
  db-internal:
    driver: bridge

volumes:
  sqlvolume: